base_url = "https://konceptosociala.eu.org"
compile_sass = true
output_dir = "docs"
default_language = "en"
build_search_index = false
theme = "socio"

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
# General
socio_title = "Koncepto Sociala"
socio_favicon = "/img/ks.svg"
socio_logo = "/img/ks.svg"
socio_animations = true

# Navbar links
socio_navbar_links = [
    { key = "home", link = "/" },
    { key = "blog", link = "/blog/" },
    { key = "games", dropdown = [
        ["komunterio", "/games/komunterio/"],
    ] },
    { key = "software", dropdown = [
        ["sonja", "/software/sonja/"],
        ["sonja_doryen", "/software/sonja-doryen/"],
    ] },
    { key = "github", link = "https://github.com/konceptosociala" },
    { key = "about", link = "/about/" }
]

# Multilingualism (uncomment to enable language switcher)
socio_languages = [
    { code = "default", name = "English", flag = "us" },
    { code = "ua", name = "Українська", flag = "ua" },
]

# Homepage banner
socio_banner_display = true
socio_banner_logo = "/img/ks.svg"
socio_banner_logo_width = 144
socio_banner_animation = "fadeIn"

# Social (comment to hide)
socio_github = "https://github.com/konceptosociala/"
socio_mail = "mailto:sanerhp.mail@gmail.com"
# socio_discord = "#"
# socio_facebook = "#"
# socio_insta = "#"
# socio_linkedin = "#"
# socio_reddit = "#"
# socio_twitter = "#"
# socio_youtube = "#"

# Colors
socio_text_color = "#F5F5F5"
socio_link_color = "#FFF"
socio_code_color = "#FFF"
socio_code_bg = "#1D1E23"

socio_post_bg = "#1D1E23"
socio_header_bg = "#0F0F11"
socio_footer_bg = "#1D1E23"
socio_404_bg = "#0F0F11"
socio_page_bg = "#393C44"
socio_banner_bg = "#1D1E23"

socio_pill_bg = "dark"
socio_project_bg = "dark"
socio_pill_btn = "primary"
socio_banner_btn = "primary"
socio_back_btn = "light"

# Misc
socio_forkme = { enabled = false, repo = "", label = ""}

# Utterances
[extra.socio_utterances]
label = "KS Comment"
repo = "konceptosociala/konceptosociala.github.io"
theme = "photon-dark"

[translations]
project_page = "Project page"
read_more = "Read more"
banner_button = "Learn more"
banner_heading = "Koncepto Sociala"
banner_descr = "Kreita esti libera."

home = "Home"
blog = "Blog"
games = "Games"
komunterio = "Komunterio"
software = "Software"
sonja = "Sonja"
sonja_doryen = "Sonja Doryen"
github = "GitHub"
about = "About"

[languages.ua]

[languages.ua.translations]
project_page = "Сторінка проєкту"
read_more = "Детальніше"
banner_button = "Дізнатися більше"
banner_heading = "Koncepto Sociala"
banner_descr = "Створена бути вільною."

home = "Головна"
blog = "Блог"
games = "Ігри"
komunterio = "Komunterio"
software = "ПЗ"
sonja = "Sonja"
sonja_doryen = "Sonja Doryen"
github = "GitHub"
about = "Про нас"