base_url = "https://konceptosociala.eu.org"
compile_sass = true
output_dir = "docs"
build_search_index = true
theme = "socio"

[markdown]
highlight_code = true

[extra]
# General
socio_title = "Koncepto Sociala"
socio_favicon = "/img/ks.svg"
socio_logo = "/img/ks.svg"

# Navbar links
socio_navbar_links = [
    { title = "Home", link = "/" },
    { title = "Blog", link = "/blog/" },
    { title = "Software", dropdown = [
        ["Sonja", "/software/sonja/"],
        ["...", "..."]
    ] },
    { title = "GitHub", link = "https://github.com/konceptosociala" },
    { title = "About", link = "/about/" }
]

# Homepage banner
socio_banner_display = true
socio_banner_logo = "/img/ks.svg"
socio_banner_logo_width = 144
socio_banner_heading = "Koncepto Sociala"
socio_banner_descr = "Kreita esti libera."

# Social (comment to hide)
socio_github = "https://github.com/konceptosociala/socio"
socio_mail = "mailto:sanerhp.mail@gmail.com"
socio_telegram = "https://t.me/ksociala_official"
# socio_discord = "#"
# socio_facebook = "#"
# socio_insta = "#"
# socio_linkedin = "#"
# socio_reddit = "#"
# socio_twitter = "#"
# socio_youtube = "#"

# Colors
socio_text_color = "#F5F5F5"
socio_link_color = "#F5F5F5"
socio_code_color = "#F5F5F5"
socio_code_bg = "#2b303b"

socio_post_bg = "#40312F"
socio_header_bg = "#29201E"
socio_footer_bg = "#49403E"
socio_404_bg = "#695451"
socio_page_bg = "#695451"
socio_banner_bg = "#49403E"

socio_banner_btn = "success"
socio_search_btn = "light"

# Misc
socio_forkme = { enabled = false, repo = "", label = ""}
